# Generated by Django 4.0.5 on 2022-11-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_remove_editora_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editora',
            name='cidade',
        ),
        migrations.AddField(
            model_name='editora',
            name='modalidade',
            field=models.CharField(choices=[('B', 'bacharelado'), ('L', 'licenciatura'), ('T', 'tecnológico')], max_length=1, null=True),
        ),
    ]
