# Generated by Django 4.0.5 on 2022-11-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_remove_editora_cidade_editora_modalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editora',
            name='modalidade',
            field=models.CharField(choices=[('Bacharelado', 'bacharelado'), ('L', 'licenciatura'), ('T', 'tecnológico')], max_length=100, null=True),
        ),
    ]
