# Generated by Django 4.0.5 on 2022-11-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_alter_autor_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.ImageField(default=None, upload_to='capas/'),
        ),
    ]
