# Generated by Django 4.0.5 on 2022-11-24 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0007_orientador'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='orientador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='livros.orientador'),
        ),
        migrations.RemoveField(
            model_name='livro',
            name='autor',
        ),
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='livros.autor'),
        ),
    ]
