# Generated by Django 4.0.5 on 2022-11-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0009_alter_livro_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='editora',
            new_name='curso',
        ),
    ]
