# Generated by Django 4.0.5 on 2022-11-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0012_rename_livro_pdf_livro_tcc_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='genero',
            new_name='pchave',
        ),
        migrations.AlterField(
            model_name='livro',
            name='tcc_pdf',
            field=models.FileField(upload_to='livros/', verbose_name='TCC em PDF'),
        ),
    ]
